server:
  port: 8000

spring:
  application:
    name: weeklyEurekaRegister8000

eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
              defaultZone: http://weeklyEureka8000:8000/eureka/
    instance:
      hostname: weeklyEureka8000